variant_list: '/vol/bmd/yanyul/GitHub/ptrs-ukb/output/variant_list_as_ld_reference.txt'
individual_list: '/vol/bmd/yanyul/GitHub/ptrs-ukb/output/indiv_list_as_ld_reference.txt'
bgen: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb_imp_chr{chr_num}_v3.bgen'
sample: '/vol/bmd/data/ukbiobank/genotypes/v3/ukb19526_imp_chr1_v3_s487395.sample'
chr_num: 22
plink2_path: '/vol/bmd/yanyul/softwares/plink2'
plink_memory_in_mb: 50000
plink_threads: 4

