bgen: '/gpfs/data/im-lab/nas40t2/yanyul/PTRS/subset_bgen/subset_chr{chr_num}.bgen'
sample: '/gpfs/data/im-lab/nas40t2/yanyul/PTRS/subset_bgen/subset_chr{chr_num}.sample'
plink2_cmd: '/gpfs/data/im-lab/nas40t2/yanyul/softwares/plink2'
plink_memory_in_mb: 16000
plink_threads: 1
outdir: '/scratch/t.cri.yliang/PTRS/subset_british_cleaned_up_vcf'

